FROM oven/bun:1.3.14-alpine AS base

# Install dependencies only when needed
FROM base AS deps
WORKDIR /app

# Install pnpm
RUN bun add -g pnpm

# Copy only package.json
COPY package.json ./

# Install dependencies and create bun.lockb
RUN --mount=type=cache,id=bun,target=/root/.bun \
    bun install

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app

# Declare ARGs for all environment variables
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID

# Convert ARGs to ENVs
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$NEXT_PUBLIC_GOOGLE_ANALYTICS_ID

# Copy dependencies and source code
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build with cache
RUN --mount=type=cache,target=/app/.next/cache \
    bun run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

RUN adduser --system --uid 1001 nextjs

# Copy static files
COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next && chown nextjs:bun .next

# Copy build files
COPY --from=builder --chown=nextjs:bun /app/.next/standalone ./
COPY --from=builder --chown=nextjs:bun /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["bun", "server.js"]
